// Centralized icon set (Phosphor) — keeps icon choices consistent across the app.
// Swap an emoji here once and it updates everywhere.
export {
    Broom as ChoreIcon,
    SprayBottle as ViledaIcon,
    Island as HolidayIcon,
    Printer as PrintIcon,
    X as CloseIcon,
    CalendarBlank as CalendarIcon,
    GearSix as AdminIcon,
    Users as MembersIcon,
    TelegramLogo as TelegramIcon,
    PaperPlaneTilt as SendIcon,
    TestTube as TestIcon,
    ArrowsClockwise as SyncIcon,
    ChartBar as StatsIcon,
    CaretLeft as PrevIcon,
    CaretRight as NextIcon,
    Confetti as PartyIcon,
    Trophy as TrophyIcon,
    SignOut as LogoutIcon,
    SpinnerGap as SpinnerIcon,
    Plus as PlusIcon,
    Trash as TrashIcon,
    CheckCircle as CheckIcon,
    XCircle as ErrorIcon,
    Warning as WarningIcon,
    LockKey as LockIcon,
    SignIn as SignInIcon,
    DiceFive as WheelIcon,
    Pause as PauseIcon,
    Play as PlayIcon,
} from '@phosphor-icons/react';
